[package]
name = "leo-lang"
version = "1.5.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "The Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
][package]
name = "leo-lang"
version = "1.5.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "The Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "leo", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"
rust-version = "1.56.1"

[lib]
path = "leo/lib.rs"

[[bin]]
name = "leo"
path = "leo/main.rs"

[workspace]
members = [
  "compiler/compiler",
  "docs/grammar",
  "leo/errors",
  "leo/package",
  "tests/test-framework",
]

[dependencies.leo-compiler]
path = "./compiler/compiler"
version = "1.5.3"

[dependencies.leo-errors]
path = "./leo/errors"
version = "1.5.3"

[dependencies.leo-package]
path = "./leo/package"
version = "1.5.3"

[dependencies.snarkvm-utilities]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "51633e2"

[dependencies.clap]
version = "3.1"

[dependencies.color-backtrace]
version = "0.5.1"

[dependencies.colored]
version = "2.0"

[dependencies.dirs]
version = "4.0.0"

[dependencies.console]
version = "0.15.0"

[dependencies.indexmap]
version = "1.8"
features = ["serde"]

[dependencies.lazy_static]
version = "1.4.0"

[dependencies.notify]
version = "4.0.17"

[dependencies.rand]
version = "0.8"

[dependencies.rand_core]
version = "0.6.3"

[dependencies.reqwest]
version = "0.11.10"
features = [ "blocking", "json", "multipart" ]

[dependencies.self_update]
version = "0.29.0"
features = [ "archive-zip" ]

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.serde_json]
version = "1.0"

[dependencies.structopt]
version = "0.3"

[dependencies.toml]
version = "0.5"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.3.10"
features = [ "fmt" ]

[dependencies.zip]
version = "0.6"

[target."cfg(windows)".dependencies.ansi_term]
version = "0.12.1"

[dev-dependencies.assert_cmd]
version = "2.0.4"

[dev-dependencies.rusty-hook]
version = "0.11.2"

[dev-dependencies.test_dir]
version = "0.1.0"

[features]
default = [ ]
ci_skip = [ "leo-compiler/ci_skip" ]
noconfig = [ ]

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 0
debug-assertions = true
debug = true
